In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("AdultIncome.csv")

In [5]:
df.head(3)

age        wc   education  ...   gender hours per week IncomeClass
0   38   Private     HS-grad  ...     Male             40       <=50K
1   28   Private   Bachelors  ...   Female             40       <=50K
2   37   Private     Masters  ...   Female             40       <=50K

[3 rows x 8 columns]

In [4]:
df.isnull().sum()

age               0
wc                0
education         0
marital status    0
race              0
gender            0
hours per week    0
IncomeClass       0
dtype: int64

In [7]:
df = pd.get_dummies(df,drop_first=True)

In [8]:
df.head()

age  hours per week  ...  gender_ Male  IncomeClass_ >50K
0   38              40  ...             1                  0
1   28              40  ...             0                  0
2   37              40  ...             0                  0
3   31              50  ...             0                  1
4   42              40  ...             1                  1

[5 rows x 20 columns]

In [9]:
df

age  hours per week  ...  gender_ Male  IncomeClass_ >50K
0       38              40  ...             1                  0
1       28              40  ...             0                  0
2       37              40  ...             0                  0
3       31              50  ...             0                  1
4       42              40  ...             1                  1
...    ...             ...  ...           ...                ...
19782   53              40  ...             1                  1
19783   22              40  ...             1                  0
19784   40              40  ...             1                  1
19785   58              40  ...             0                  0
19786   22              20  ...             1                  0

[19787 rows x 20 columns]

In [12]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [13]:
y

array([0, 0, 0, ..., 1, 0, 0], dtype=uint8)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=0)

In [15]:
y_train

array([1, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [16]:
x_test

array([[33, 45,  0, ...,  0,  1,  1],
       [53, 50,  1, ...,  0,  1,  0],
       [31, 45,  0, ...,  0,  1,  1],
       ...,
       [35, 30,  0, ...,  0,  1,  0],
       [32, 60,  0, ...,  0,  1,  1],
       [27, 40,  0, ...,  0,  1,  1]])

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
dtc = DecisionTreeClassifier(random_state=0)
dtc.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [20]:
pred_y = dtc.predict(x_test)

In [21]:
pred_y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,pred_y)

array([[3154,  461],
       [ 633,  699]])

In [24]:
accuracy_score(y_test,pred_y)

0.7788558722458055

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state =0)
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [26]:
y_predrfc = rfc.predict(x_test)

In [27]:
confusion_matrix(y_test,y_predrfc)

array([[3181,  434],
       [ 571,  761]])

In [28]:
accuracy_score(y_test,y_predrfc)

0.7968465736810187