In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

In [27]:
# step1: take the data
df = pd.read_csv("/content/LSM1.csv")

In [28]:
# step2: filter the data
# step3: divide into the input and output, x-->input, y-->output
# retrive the x and y value from the dataframe
x = df.iloc[:,0].values.reshape(5,1)
y = df.iloc[:,1].values

(5, 1)

In [24]:
# create an object  since we cant use the a class directly
Lin = LinearRegression()

In [29]:
# training the model
Lin.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
Lin.predict([[2.5]])

array([3.7])

In [33]:
Lin.coef_

array([0.6])

In [34]:
Lin.fit_intercept

True

In [35]:
Lin.intercept_

2.2

In [36]:
Lin.singular_

array([3.16227766])

In [38]:
x

array([[1],
       [2],
       [3],
       [4],
       [5]])