In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("/content/Salary_Data.csv")
df.head(2)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0

In [5]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [6]:
x = df.iloc[:,0].values.reshape(-1,1)

In [7]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [8]:
y = df.iloc[:,1].values

In [9]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_x, test_x, train_y, test_y = train_test_split(x,y, test_size=0.2, random_state=0)

In [12]:
test_x

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7]])

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
Lin = LinearRegression()
Lin.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
Lin.intercept_

26780.09915062818

In [17]:
pred_y = Lin.predict(test_x)

In [18]:
# pred_y is the predicted value 
# test_y is the actual value

Error Evaluation
1. MAE Mean Absolute Error
2. MSE Mean Squared Error

In [19]:
pred_y-test_y

array([ 3017.96184072,   308.62295594,  7880.65717022,  -118.85785513,
       -1719.43714544, -1631.49724683])

In [22]:
np.abs(pred_y-test_y).mean()

2446.1723690465055

In [26]:
((pred_y-test_y)**2).mean()

12823412.298126549

In [28]:
from sklearn import metrics

In [30]:
metrics.mean_absolute_error(test_y,pred_y)

2446.1723690465055

In [31]:
metrics.mean_squared_error(test_y,pred_y)

12823412.298126549